replicaCount: 1

image:
  repository: resource-service
  tag: latest

service:
  port: 8081

env:
  - name: EXAMPLE_ENV
    value: "default-value"
  - name: SPRING_DATASOURCE_URL
    value: ""
  - name: POSTGRES_DB_USER
    value: ""
  - name: POSTGRES_DB_PASSWORD
    value: ""
  - name: SONG_SERVICE_URL
    value: ""
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: ""
  - name: WEB_APP_TYPE
    value: ""
