replicaCount: 1

image:
  repository: resource-service
  tag: latest
  pullPolicy: Never

service:
  port: 8081

env:
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://postgres-resource:5432/resource-db"
  - name: POSTGRES_DB_USER
    value: "moduleuser"
  - name: POSTGRES_DB_PASSWORD
    value: "password"
  - name: SONG_SERVICE_URL
    value: "http://gateway:8080/songs"
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: "http://discovery:8761/eureka/"
  - name: WEB_APP_TYPE
    value: "servlet"
