replicaCount: 2

image:
  repository: song-service
  tag: latest
  pullPolicy: Never

service:
  port: 8082

env:
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://postgres-song:5432/song-db"
  - name: POSTGRES_DB_USER
    value: "moduleuser"
  - name: POSTGRES_DB_PASSWORD
    value: "password"
  - name: RESOURCE_SERVICE_URL
    value: "http://gateway:8080/resources"
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: "http://discovery-discovery:8761/eureka/"
  - name: WEB_APP_TYPE
    value: "servlet"
