apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresResource.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresResource.port }}
      targetPort: 5432
  selector:
    app: {{ .Values.postgresResource.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgresResource.name }}
spec:
  serviceName: {{ .Values.postgresResource.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgresResource.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresResource.name }}
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresResource.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresResource.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresResource.password | quote }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          emptyDir: {}
