apiVersion: v1
kind: Service
metadata:
  name: {{ include "discovery.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "discovery.name" . }}
